### ISSUE TITLE
ImportError: DLL load failed while importing _dlib_pybind11

### ISSUE THREAD

**Issue by Darshan1412** [abbasmammadov/Artificial-Barber#1]
![image](https://github.com/abbasmammadov/Artificial-Barber/assets/89580717/2492f365-2186-4264-85f4-4c6dc775e5cf)

how do i solve this error ?

**Comment by abbasmammadov** [comment]
Hello, 

I suppose the issue was caused during the very initial stage i.e. while importing dlib. There can be several reasons, but I believe the problem is about the installation of dlib. I recommend you to reinstall the dlib with various other methods, not only pip (un)install ..., e.g. building from scratch can be another solution:
1. pip uninstall/install dlib
2. pip install again but specify the version
3. make sure that the environment you are using is the environment with appropriate installation(s)
4. build from scratch
5. ...

For your information, throughout the project all the experiments were conducted with conda environments. That can be another way to solve by utilizing conda env and install all the dependencies.

Just in case also make sure that your device is equipped with NVIDIA GPU and CUDA CuDNN.
